language: elixir
elixir:
  - 1.6
  - 1.5
  - 1.4
otp_release:
  - 19.0
  - 18.3
  - 18.2
sudo: false
script:
  - "MIX_ENV=test mix do deps.get, test && mix compile && MIX_ENV=test mix coveralls.travis"