language: elixir
elixir:
  - 1.7
  - 1.6
  - 1.5
  - 1.4
otp_release:
  - 21
  - 20
  - 19
sudo: false
script:
  - "MIX_ENV=test mix do deps.get, test && mix compile && MIX_ENV=test mix coveralls.travis"